homebrew_taps: [] 

homebrew_installed_packages:
  - dockutil
  - font-jetbrains-mono

homebrew_cask_apps:
  - 1password
  - ghostty

pip_items: []

gem_items: []

npm_items: []

dockitems_to_remove:
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Phone
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - TV
  - Music
  - Games
  - App Store
  - iPhone Mirroring
  - System Settings

dockitems_to_persist:
  - name: Safari
    path: "/Applications/Safari.app"
    pos: 2
