---
- hosts: all
  connection: local

  vars_files:
    - config.yml

  roles:
    - role: geerlingguy.mac.homebrew
    - role: geerlingguy.mac.mas
      when: sysctl_vm_check.stdout == "0"
    - role: localconfig