---
- hosts: all
  connection: local

  environment:
    PATH: "/opt/homebrew/bin:{{ ans_env.PATH | default('/usr/bin:/bin:/usr/sbin:/sbin') }}"

  vars_files:
    - config.yml

  tasks:
    - name: Check if running inside a Virtual Machine
      ansible.builtin.command: sysctl -n kern.hv_vmm_present
      register: sysctl_vm_check
      changed_when: false
    
    - name: Include Homebrew role
      ansible.builtin.include_role:
        name: geerlingguy.mac.homebrew

    - name: Include Mac App Store role (Physical hardware only)
      ansible.builtin.include_role:
        name: geerlingguy.mac.mas
      when: sysctl_vm_check.stdout == "0"

    - name: Incloude local configuration role
      ansible.builtin.include_role:
        name: localconfig